name: This is my first workflow
on:
   push:
       branches:
             -main

jobs:
    testjob:
      run-on: ubuntu-latest
      steps: 
        - name: echo a string
          run: echo "hello world"