name: This is my first workflow
on:
   push:
       branches:
             -main

jobs:
   build:
     name: build
     runs-on: ubuntu-latest

     steps:
        -name: echo a string
         run: echo 'hello my first workflow'
        
         
         
